### Import Libraries

In [1]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup

from selenium import webdriver
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys

import time

### Web Scraping Player Hyperlinks

In [2]:
# Create an function for getting soup object
def get_soup_object(url):

    # Define url and user-agent
    user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'

    # Set the user agent string in the headers
    headers = {
        'User-Agent': user_agent
    }

    # Make the request using the headers
    response = requests.get(url, headers=headers)

    # Parse the HTML content using Beautiful Soup
    soup = BeautifulSoup(response.content, 'html.parser')

    return soup

In [3]:
def get_win_loss_stats(soup, index_name):

    for row in soup.find_all('tr'):
        print
        if (index_name in row.text) & (len(row.find_all('td'))==3):
            if (row.find('td').text==index_name):
                stats = row.find_all('td')[2].text
                wins = int(stats.split('/')[0].strip())
                losses = int(stats.split('/')[1].strip())
                break
            else:
                wins = np.nan
                losses = np.nan
        else:
            wins = np.nan
            losses = np.nan
    return wins, losses

In [4]:
def get_serve_return_stats(soup, index_name):

    for row in soup.find_all('tr'):
        if (index_name in row.text) & (len(row.find_all('td'))==3):
            stats = row.find_all('td')[2].text
            num = int(stats.split('/')[0].strip())
            total = int(stats.split('/')[1].strip())
            break
                
    return num, total

In [5]:
def get_win_loss_stats_by_year(soup, player_dict, year):

    player_dict['wins_' + str(year)] = get_win_loss_stats(soup, 'Overall')[0]
    player_dict['losses_' + str(year)] = get_win_loss_stats(soup, 'Overall')[1]
    player_dict['hard_wins_' + str(year)] = get_win_loss_stats(soup, 'Hard')[0]
    player_dict['hard_losses_' + str(year)] = get_win_loss_stats(soup, 'Hard')[1]
    player_dict['clay_wins_' + str(year)] = get_win_loss_stats(soup, 'Clay')[0]
    player_dict['clay_losses_' + str(year)] = get_win_loss_stats(soup, 'Clay')[1]   
    player_dict['grass_wins_' + str(year)] = get_win_loss_stats(soup, 'Grass')[0]
    player_dict['grass_losses_' + str(year)] = get_win_loss_stats(soup, 'Grass')[1]
    player_dict['final_wins_' + str(year)] = get_win_loss_stats(soup, 'F')[0]
    player_dict['final_losses_' + str(year)] = get_win_loss_stats(soup, 'F')[1]    
    player_dict['semifinal_wins_' + str(year)] = get_win_loss_stats(soup, 'SF')[0]
    player_dict['semifinal_losses_' + str(year)] = get_win_loss_stats(soup, 'SF')[1]
    player_dict['quarterfinal_wins_' + str(year)] = get_win_loss_stats(soup, 'QF')[0]
    player_dict['quarterfinal_losses_' + str(year)] = get_win_loss_stats(soup, 'QF')[1]
    player_dict['round4_wins_' + str(year)] = get_win_loss_stats(soup, '4th Round')[0]
    player_dict['round4_losses_' + str(year)] = get_win_loss_stats(soup, '4th Round')[1]
    player_dict['round3_wins_' + str(year)] = get_win_loss_stats(soup, '3rd Round')[0]
    player_dict['round3_losses_' + str(year)] = get_win_loss_stats(soup, '3rd Round')[1]
    player_dict['round2_wins_' + str(year)] = get_win_loss_stats(soup, '2nd Round')[0]
    player_dict['round2_losses_' + str(year)] = get_win_loss_stats(soup, '2nd Round')[1]
    player_dict['round1_wins_' + str(year)] = get_win_loss_stats(soup, '1st Round')[0]
    player_dict['round1_losses_' + str(year)] = get_win_loss_stats(soup, '1st Round')[1]
    player_dict['grand_slam_wins_' + str(year)] = get_win_loss_stats(soup, 'Grand Slam')[0]
    player_dict['grand_slam_losses_' + str(year)] = get_win_loss_stats(soup, 'Grand Slam')[1]
    player_dict['masters_wins_' + str(year)] = get_win_loss_stats(soup, 'Masters')[0]
    player_dict['masters_losses_' + str(year)] = get_win_loss_stats(soup, 'Masters')[1]
    player_dict['main_tour_wins_' + str(year)] = get_win_loss_stats(soup, 'Main Tour')[0]
    player_dict['main_tour_losses_' + str(year)] = get_win_loss_stats(soup, 'Main Tour')[1]
    player_dict['cup_wins_' + str(year)] = get_win_loss_stats(soup, 'Cups')[0]
    player_dict['cup_losses_' + str(year)] = get_win_loss_stats(soup, 'Cups')[1]
    player_dict['vsTop5_wins_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.5')[0]
    player_dict['vsTop5_losses_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.5')[1]
    player_dict['vsTop10_wins_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.10')[0]
    player_dict['vsTop10_losses_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.10')[1]
    player_dict['vsTop20_wins_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.20')[0]
    player_dict['vsTop20_losses_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.20')[1]
    player_dict['vsTop50_wins_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.50')[0]
    player_dict['vsTop50_losses_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.50')[1]
    player_dict['vsTop100_wins_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.100')[0]
    player_dict['vsTop100_losses_' + str(year)] = get_win_loss_stats(soup, 'Vs Top.100')[1]

    return player_dict

In [6]:
def get_serve_return_stats_by_year(soup, player_dict, year):

    player_dict['aces_' + str(year)] = get_serve_return_stats(soup, 'Aces per Game')[0]
    player_dict['opp_aces_' + str(year)] = get_serve_return_stats(soup, 'Opp Aces per Game')[0]
    player_dict['total_games_' + str(year)] = get_serve_return_stats(soup, 'Aces per Game')[1]
    player_dict['DFs_' + str(year)] = get_serve_return_stats(soup, 'DFs per Game')[0]
    player_dict['opp_DFs_' + str(year)] = get_serve_return_stats(soup, 'Opp DFs per Game')[0]
    player_dict['1st_serve_%_' + str(year)] = get_serve_return_stats(soup, '1st Serve %')[0]
    player_dict['1st_serve_%_total_' + str(year)] = get_serve_return_stats(soup, '1st Serve %')[1]
    player_dict['1st_serve_win_%_' + str(year)] = get_serve_return_stats(soup, '1st Serve Win%')[0]
    player_dict['1st_serve_win_%_total_' + str(year)] = get_serve_return_stats(soup, '1st Serve Win%')[1]
    player_dict['2nd_serve_win_%_' + str(year)] = get_serve_return_stats(soup, '2nd Serve Win%')[0]
    player_dict['2nd_serve_win_%_total_' + str(year)] = get_serve_return_stats(soup, '2nd Serve Win%')[1]
    player_dict['serve_pts_win_%_' + str(year)] = get_serve_return_stats(soup, 'Serve Pts Win%')[0]
    player_dict['serve_pts_win_%_total_' + str(year)] = get_serve_return_stats(soup, 'Serve Pts Win%')[1]
    player_dict['opp_1st_serve_%_' + str(year)] = get_serve_return_stats(soup, 'Opp 1st Serve %')[0]
    player_dict['opp_1st_serve_%_total_' + str(year)] = get_serve_return_stats(soup, 'Opp 1st Serve %')[1]
    player_dict['1st_rtn_win_%_' + str(year)] = get_serve_return_stats(soup, '1st Rtn Win%')[0]
    player_dict['1st_rtn_win_%_total_' + str(year)] = get_serve_return_stats(soup, '1st Rtn Win%')[1]
    player_dict['2nd_rtn_win_%_' + str(year)] = get_serve_return_stats(soup, '2nd Rtn Win%')[0]
    player_dict['2nd_rtn_win_%_total_' + str(year)] = get_serve_return_stats(soup, '2nd Rtn Win%')[1]
    player_dict['rtn_pts_win_%_' + str(year)] = get_serve_return_stats(soup, 'Rtn Pts Win%')[0]
    player_dict['rtn_pts_win_%_total_' + str(year)] = get_serve_return_stats(soup, 'Rtn Pts Win%')[1]
    player_dict['bps_saved_' + str(year)] = get_serve_return_stats(soup, 'BPs Saved per game')[0]        
    player_dict['bps_faced_' + str(year)] = get_serve_return_stats(soup, 'BPs Faced per game')[0]
    player_dict['bp_save_' + str(year)] = get_serve_return_stats(soup, 'BP Save %')[0]
    player_dict['bp_save_total_' + str(year)] = get_serve_return_stats(soup, 'BP Save %')[1]
    player_dict['service_hold_' + str(year)] = get_serve_return_stats(soup, 'Service Hold %')[0]     
    player_dict['bps_won_' + str(year)] = get_serve_return_stats(soup, 'BPs Won per game')[0]     
    player_dict['bps_opps_' + str(year)] = get_serve_return_stats(soup, 'BPs Opps per game')[0]     
    player_dict['bps_won_%' + str(year)] = get_serve_return_stats(soup, 'BP Won %')[0]
    player_dict['bps_won_%_total_' + str(year)] = get_serve_return_stats(soup, 'BP Won %')[1]     
    player_dict['opp_hold_' + str(year)] = get_serve_return_stats(soup, 'Opp Hold %')[0]
    
    return player_dict

In [7]:
def perform_win_loss_scraping(driver, player_dict):

    dropdown_xpath = '/html/body/app-root/div[2]/app-profile/div/div/div[1]/div[2]/app-profile-performance-breakdown/div[1]/div/h1/app-profile-performance-year-picker/div/a'

    try:
        
        for year_index in range(2, 20):
            year = 2025 - year_index

            # Wait for the dropdown link to be clickable
            wait = WebDriverWait(driver, 1)
            dropdown_link = wait.until(EC.element_to_be_clickable((By.XPATH, dropdown_xpath)))

            # Click the dropdown link to open the year options using JavaScript
            driver.execute_script("arguments[0].click();", dropdown_link)
            
            # Find the year option for the current year_index
            year_xpath = f'/html/body/app-root/div[2]/app-profile/div/div/div[1]/div[2]/app-profile-performance-breakdown/div[1]/div/h1/app-profile-performance-year-picker/div/div/div/div/ul/li[{year_index}]/a'
            year_option = driver.find_element(By.XPATH, year_xpath)

            # Scroll to the year option using JavaScript
            driver.execute_script("arguments[0].scrollIntoView(true);", year_option)

            # Click the year option for the current year_index using JavaScript
            driver.execute_script("arguments[0].click();", year_option)

            # Get the HTML content of the page after selecting the year option
            soup = BeautifulSoup(driver.page_source, 'html.parser')

            # Perform the scraping for the current year
            get_win_loss_stats_by_year(soup, player_dict, year)

    except:
        return player_dict

    
    return player_dict

In [8]:
def perform_serve_return_scraping(driver, player_dict):

    # Find the parent div element by class
    parent_div = driver.find_element(By.XPATH, '//div[@class="col col-md-2 p-1 p-md-2"]')

    # Find the dropdown element within the parent div
    dropdown = Select(parent_div.find_element(By.CLASS_NAME, 'bg-white'))

    # Get the options in the dropdown menu
    options = dropdown.options

    # Iterate through each option and select it
    for option in options:
        
        # Get each year from the dropdown menu
        year = option.text 

        # Select the option
        dropdown.select_by_visible_text(year)

        # Allow time to load the page
        time.sleep(0.5)

        # Get the HTML content of the page after selecting the year option
        soup = BeautifulSoup(driver.page_source, 'html.parser')

        # Perform the webscraping
        get_serve_return_stats_by_year(soup, player_dict, year)

    return player_dict

In [9]:
def get_player_data(url):

    # Create an empty dictionary
    player_dict = {}

    # Configure the Selenium webdriver
    driver = webdriver.Chrome()  # You may need to download the appropriate driver for your browser (e.g., ChromeDriver)

    try:

        # Navigate to the webpage
        driver.get(url)


        # Get soup object
        soup = BeautifulSoup(driver.page_source, 'html.parser')

        # Wait two minutes if 505 error
        if ('505 Gateway Timeout' in soup.text) or ("This site can't be reached" in soup.text) or ('Your connection was interrupted' in soup.text):
            time.sleep(120)
            driver.get(url)
            soup = BeautifulSoup(driver.page_source, 'html.parser')

        
        # Get player name
        player_dict['name'] = soup.find('h4').text

        # Perform win and loss scraping 
        perform_win_loss_scraping(driver, player_dict)

        # Perform serve and return scraping
        perform_serve_return_scraping(driver, player_dict)
            
        # Close the web driver
        driver.quit()
    except:
        print('Error: Waiting 2 mins before trying again')
        driver.quit()
        time.sleep(120)
        get_player_data(url)


    return player_dict

In [22]:
def get_player_urls(url):

    player_urls = []

    # Set up Selenium to use a headless Chrome browser
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    driver = webdriver.Chrome(options=options)

    driver.get(url)

    # Wait for the table to load by checking for a specific element on the page
    # that appears only after the table has been generated by JavaScript
    driver.implicitly_wait(3) 
    
    element = driver.find_elements('css selector', "#table-loaded")

    # Click the "show more" button if it's present
    while True:
        try:
            show_more_button = driver.find_elements('xpath', '/html/body/app-root/div/app-rankings/div/div/div[1]/div[8]/div/button')
            if len(show_more_button) > 0:
                driver.execute_script("arguments[0].click();", show_more_button[0])
                time.sleep(2) # wait for the new data to load
            else:
                break
        except:
            print('no button found')
            break

    driver.implicitly_wait(5) # wait for up to 10 seconds
    element = driver.find_elements('css selector', "#table-loaded")

    # Extract the HTML code of the entire page, including the dynamically generated table
    html = driver.page_source

    # Parse the HTML code using Beautiful Soup
    soup = BeautifulSoup(html, "html.parser")

    # Find the table using Beautiful Soup's find() or find_all() method
    table = soup.find("table")

    # Extract the data from the table as needed
    rows = table.find_all("tr")

    for row in rows[1:]:
        url_suffix = row.find('a')['href']
        player_url = 'https://matchstat.com/' + url_suffix
        player_urls.append(player_url)

    driver.close()

    return player_urls

In [23]:
player_urls = get_player_urls('https://matchstat.com/tennis/atp-wta-rankings')

In [24]:
len(player_urls)

900

In [25]:
all_player_atts = []

In [26]:
for url in player_urls:

    player_atts = get_player_data(url)
    all_player_atts.append(player_atts)
    if len(all_player_atts) % 100 == 0:
        print('100 players checked')

Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked
100 players checked
100 players checked
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
Error: Waiting 2 mins before trying again
100 players checked

100

In [27]:
pd.DataFrame(all_player_atts).to_csv('all_player_atts2.csv', index=False)

In [23]:
df = pd.read_csv('all_player_atts.csv')
df.head()

,name,wins_2023,losses_2023,hard_wins_2023,hard_losses_2023,clay_wins_2023,clay_losses_2023,grass_wins_2023,grass_losses_2023,final_wins_2023,...,bps_saved_2003,bps_faced_2003,bp_save_2003,bp_save_total_2003,service_hold_2003,bps_won_2003,bps_opps_2003,bps_won_%2003,bps_won_%_total_2003,opp_hold_2003
0,Carlos Alcaraz,45.0,4.0,10.0,1.0,25.0,3.0,10.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Novak Djokovic,32.0,4.0,15.0,1.0,12.0,3.0,5.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Daniil Medvedev,46.0,8.0,24.0,3.0,10.0,3.0,7.0,2.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Casper Ruud,23.0,13.0,5.0,6.0,17.0,6.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Stefanos Tsitsipas,35.0,13.0,11.0,3.0,17.0,5.0,4.0,4.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Iterate through each dropdown option (year)
for option in options:
    year = option.text  # Assuming the option text represents the year
    
    # Click on the dropdown option to select it
    option.click()
    
    # Wait for the necessary data to load or perform any required actions
    WebDriverWait(driver, 10).until(
        # Update the condition based on the data you need to extract
        EC.presence_of_element_located((By.CLASS_NAME, "data-element"))
    )
    
    # Scrape the desired data for the selected year
    # ...
    # Your scraping code here
    # ...
    
    # Print or process the scraped data for the selected year
    print("Year:", year)
    # ...
    # Your code to handle the scraped data here
    # ...
    
# Close the browser
driver.quit()

In [3]:
# Create a function for adding player hyperlinks to a list
def get_player_links(url, player_list):

    # Get soup object
    soup = get_soup_object(url)

    # Create a copy of the list
    player_list2 = player_list.copy()

    # Loop through links and add player link if not already added
    for player in soup.find_all('a', class_='list-group-item'):
        player_link = 'https://s5.sir.sportradar.com' + player['href']
        if player_link not in player_list2:
            player_list2.append(player_link)

    return player_list2

We can create a function to return NaN if theres an error:

In [4]:
def safe_extract(fn):
    try:
        return fn()
    except:
        return np.nan

We now define a functiont to get all of a plyer's attributes from their profile page:

In [5]:
def get_player_atts(url):

    # Get soup object 
    soup = get_soup_object(url)

    if 'Access Denied' in soup.text:
        print('Access Denied for tournament', url)
        time.sleep(600)  # Wait for 10 minutes
        soup = get_soup_object(url)
        

    # Get row names
    for row in soup.find_all('tr'):
        if 'Country' in row.text:
            country_row = row
        elif 'birth' in row.text:
            dob_row = row
        elif  'Highest ranking - Singles' in row.text:
            hrs_row = row
        elif 'Plays' in row.text:
            handed_row = row
        elif 'Turned' in row.text:
            turned_pro_row = row
        elif 'Favorite' in row.text:
            fav_surface_row = row
    try:
        stats_table = soup.find_all('table', class_ = 'table table-condensed')[0]
        all_rows = stats_table.find_all('tr')
        row_2023 = [t for t in all_rows if t.find(string='2023') is not None]
        row_2022 = [t for t in all_rows if t.find(string='2022') is not None]
        row_2021 = [t for t in all_rows if t.find(string='2021') is not None]
        row_2020 = [t for t in all_rows if t.find(string='2020') is not None]
        row_2019 = [t for t in all_rows if t.find(string='2019') is not None]
        row_2018 = [t for t in all_rows if t.find(string='2018') is not None]
        total_row = [t for t in all_rows if t.find(string='Summary') is not None]
    except:   
        row_2023 = np.nan
        row_2022 = np.nan
        row_2021 = np.nan
        row_2020 = np.nan
        row_2019 = np.nan
        row_2018 = np.nan
        total_row = np.nan

    # Get attributes
    name = safe_extract(lambda: soup.find('h1').text)
    nationality = safe_extract(lambda: country_row.find_all('td')[1].text)
    dob = safe_extract(lambda: dob_row.find_all('td')[1].text[:-5])
    highest_rank = safe_extract(lambda: hrs_row.find_all('td')[1].text[:-10])
    highest_rank_year = safe_extract(lambda: hrs_row.find_all('td')[1].text[7:-1])
    handed = safe_extract(lambda: handed_row.find_all('td')[1].text)
    turned_pro = safe_extract(lambda: turned_pro_row.find_all('td')[1].text)
    fav_surface = safe_extract(lambda: fav_surface_row.find_all('td')[1].text)
    last10_win = safe_extract(lambda: soup.find_all('div', class_='tdb-text-primary')[0].text)
    rank = safe_extract(lambda: soup.find_all('h1')[1].text)
    points = safe_extract(lambda: soup.find_all('h1')[2].text)
    rank_2023 = safe_extract(lambda: row_2023[0].find_all('td')[0].text)
    win_loss_2023 = safe_extract(lambda: row_2023[0].find_all('td')[2].text)
    win_loss_clay_2023 = safe_extract(lambda: row_2023[0].find_all('td')[3].text)
    win_loss_hardcourt_2023 = safe_extract(lambda: row_2023[0].find_all('td')[4].text)
    win_loss_indoor_2023 = safe_extract(lambda: row_2023[0].find_all('td')[5].text)
    win_loss_grass_2023 = safe_extract(lambda: row_2023[0].find_all('td')[6].text)
    win_loss_other_2023 = safe_extract(lambda: row_2023[0].find_all('td')[7].text)
    rank_2022 = safe_extract(lambda: row_2022[0].find_all('td')[0].text)
    win_loss_2022 = safe_extract(lambda: row_2022[0].find_all('td')[2].text)
    win_loss_clay_2022 = safe_extract(lambda: row_2022[0].find_all('td')[3].text)
    win_loss_hardcourt_2022 = safe_extract(lambda: row_2022[0].find_all('td')[4].text)
    win_loss_indoor_2022 = safe_extract(lambda: row_2022[0].find_all('td')[5].text)
    win_loss_grass_2022 = safe_extract(lambda: row_2022[0].find_all('td')[6].text)
    win_loss_other_2022 = safe_extract(lambda: row_2022[0].find_all('td')[7].text)
    rank_2021 = safe_extract(lambda: row_2021[0].find_all('td')[0].text)
    win_loss_2021 = safe_extract(lambda: row_2021[0].find_all('td')[2].text)
    win_loss_clay_2021 = safe_extract(lambda: row_2021[0].find_all('td')[3].text)
    win_loss_hardcourt_2021 = safe_extract(lambda: row_2021[0].find_all('td')[4].text)
    win_loss_indoor_2021 = safe_extract(lambda: row_2021[0].find_all('td')[5].text)
    win_loss_grass_2021 = safe_extract(lambda: row_2021[0].find_all('td')[6].text)
    win_loss_other_2021 = safe_extract(lambda: row_2021[0].find_all('td')[7].text)
    rank_2020 = safe_extract(lambda: row_2020[0].find_all('td')[0].text)
    win_loss_2020 = safe_extract(lambda: row_2020[0].find_all('td')[2].text)
    win_loss_clay_2020 = safe_extract(lambda: row_2020[0].find_all('td')[3].text)
    win_loss_hardcourt_2020 = safe_extract(lambda: row_2020[0].find_all('td')[4].text)
    win_loss_indoor_2020 = safe_extract(lambda: row_2020[0].find_all('td')[5].text)
    win_loss_grass_2020 = safe_extract(lambda: row_2020[0].find_all('td')[6].text)
    win_loss_other_2020 = safe_extract(lambda: row_2020[0].find_all('td')[7].text)
    rank_2019 = safe_extract(lambda: row_2019[0].find_all('td')[0].text)
    win_loss_2019 = safe_extract(lambda: row_2019[0].find_all('td')[2].text)
    win_loss_clay_2019 = safe_extract(lambda: row_2019[0].find_all('td')[3].text)
    win_loss_hardcourt_2019 = safe_extract(lambda: row_2019[0].find_all('td')[4].text)
    win_loss_indoor_2019 = safe_extract(lambda: row_2019[0].find_all('td')[5].text)
    win_loss_grass_2019 = safe_extract(lambda: row_2019[0].find_all('td')[6].text)
    win_loss_other_2019 = safe_extract(lambda: row_2019[0].find_all('td')[7].text)
    rank_2018 = safe_extract(lambda: row_2018[0].find_all('td')[0].text)
    win_loss_2018 = safe_extract(lambda: row_2018[0].find_all('td')[2].text)
    win_loss_clay_2018 = safe_extract(lambda: row_2018[0].find_all('td')[3].text)
    win_loss_hardcourt_2018 = safe_extract(lambda: row_2018[0].find_all('td')[4].text)
    win_loss_indoor_2018 = safe_extract(lambda: row_2018[0].find_all('td')[5].text)
    win_loss_grass_2018 = safe_extract(lambda: row_2018[0].find_all('td')[6].text)
    win_loss_other_2018 = safe_extract(lambda: row_2018[0].find_all('td')[7].text)
    total_win_loss = safe_extract(lambda: total_row[1].find_all('td')[2].text)
    total_win_loss_clay = safe_extract(lambda: total_row[1].find_all('td')[3].text)
    total_win_loss_hardcourt = safe_extract(lambda: total_row[1].find_all('td')[4].text)
    total_win_loss_indoor = safe_extract(lambda: total_row[1].find_all('td')[5].text)
    total_win_loss_grass = safe_extract(lambda: total_row[1].find_all('td')[6].text)
    total_win_loss_other = safe_extract(lambda: total_row[1].find_all('td')[7].text)

    # Create a dictionary
    player_dict = {
    'name': name,
    'nationality': nationality,
    'dob': dob,
    'highest_rank': highest_rank,
    'highest_rank_year': highest_rank_year,
    'handed': handed,
    'turned_pro': turned_pro,
    'fav_surface': fav_surface,
    'last10_win': last10_win,
    'rank': rank,
    'points': points,
    'rank_2023': rank_2023,
    'win_loss_2023': win_loss_2023,
    'win_loss_clay_2023': win_loss_clay_2023,
    'win_loss_hardcourt_2023': win_loss_hardcourt_2023,
    'win_loss_indoor_2023': win_loss_indoor_2023,
    'win_loss_grass_2023': win_loss_grass_2023,
    'win_loss_other_2023': win_loss_other_2023,
    'rank_2022': rank_2022,
    'win_loss_2022': win_loss_2022,
    'win_loss_clay_2022': win_loss_clay_2022,
    'win_loss_hardcourt_2022': win_loss_hardcourt_2022,
    'win_loss_indoor_2022': win_loss_indoor_2022,
    'win_loss_grass_2022': win_loss_grass_2022,
    'win_loss_other_2022': win_loss_other_2022,
    'rank_2021': rank_2021,
    'win_loss_2021': win_loss_2021,
    'win_loss_clay_2021': win_loss_clay_2021,
    'win_loss_hardcourt_2021': win_loss_hardcourt_2021,
    'win_loss_indoor_2021': win_loss_indoor_2021,
    'win_loss_grass_2021': win_loss_grass_2021,
    'win_loss_other_2021': win_loss_other_2021,
    'rank_2020': rank_2020,
    'win_loss_2020': win_loss_2020,
    'win_loss_clay_2020': win_loss_clay_2020,
    'win_loss_hardcourt_2020': win_loss_hardcourt_2020,
    'win_loss_indoor_2020': win_loss_indoor_2020,
    'win_loss_grass_2020': win_loss_grass_2020,
    'win_loss_other_2020': win_loss_other_2020,
    'rank_2019': rank_2019,
    'win_loss_2019': win_loss_2019,
    'win_loss_clay_2019': win_loss_clay_2019,
    'win_loss_hardcourt_2019': win_loss_hardcourt_2019,
    'win_loss_indoor_2019': win_loss_indoor_2019,
    'win_loss_grass_2019': win_loss_grass_2019,
    'win_loss_other_2019': win_loss_other_2019,
    'rank_2018': rank_2018,
    'win_loss_2018': win_loss_2018,
    'win_loss_clay_2018': win_loss_clay_2018,
    'win_loss_hardcourt_2018': win_loss_hardcourt_2018,
    'win_loss_indoor_2018': win_loss_indoor_2018,
    'win_loss_grass_2018': win_loss_grass_2018,
    'win_loss_other_2018': win_loss_other_2018,
    'total_win_loss': total_win_loss,
    'total_win_loss_clay': total_win_loss_clay,
    'total_win_loss_hardcourt': total_win_loss_hardcourt,
    'total_win_loss_indoor': total_win_loss_indoor,
    'total_win_loss_grass': total_win_loss_grass,
    'total_win_loss_other': total_win_loss_other
    }


    player_df = pd.DataFrame(player_dict, index=[0])

    return player_df

We can define a function to return a dataframe of all players and their attribues from a tournament URL:

In [6]:
def get_tournament_player_df(tournament_url):

    # Get player hyperlinks
    tournament_players = get_player_links(tournament_url, [])

    #Create an empty list
    player_att_list = []

    # Loop through players and get attributes
    for player in tournament_players:
        new_row = get_player_atts(player)
        column_names = new_row.columns
        player_att_list.append(new_row)

    return player_att_list

In [9]:
import concurrent.futures
import time

def check_tennis_url(page_num):
    page_url = 'https://s5.sir.sportradar.com/sportradar/en/5/season/' + str(page_num)
    soup = get_soup_object(page_url)
    if 'Tennis' in soup.text and 'Doubles' not in soup.text and 'Simulated' not in soup.text and 'Table' not in soup.text:
        return page_url
    elif 'Access Denied' in soup.text:
        print(f"Access to page {page_num} is currently denied. Waiting 10 minutes before retrying...")
        time.sleep(605) 
        check_tennis_url(page_num)
    else:
        return None

tennis_urls = []

with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
    future_to_page_num = {executor.submit(check_tennis_url, page_num): page_num for page_num in range(70000, 110000)}
    for i, future in enumerate(concurrent.futures.as_completed(future_to_page_num), 1):
        page_num = future_to_page_num[future]
        try:
            tennis_url = future.result()
            if tennis_url:
                tennis_urls.append(tennis_url)
        except Exception as exc:
            print(f"Page {page_num} generated an exception: {exc}")

        if i % 5000 == 0:
            print(f"{i} page numbers checked")

In [10]:
# Check the number of tournaments 
print('Number of tournaments added:', len(tennis_urls))

Number of tournaments added: 4134

Since this would have also added Table Tennis tournaments, we will need to remove these. We also need to remove and doubles or simulated reality tournaments:

We can save this list of urls to a file for future reference:

In [11]:
# Convert to dataframe
tennis_url_df = pd.DataFrame(tennis_urls)

# Save to file
tennis_url_df.to_csv('tennis_tournament_urls.csv', index=False)

## Creating a Dataset of Player Attributes

In [7]:
# Load tournament urls
tennis_url_df = pd.read_csv('tennis_tournament_urls.csv')

# Convert to list
tournament_list = tennis_url_df['0'].to_list()

In [8]:
import concurrent.futures
import requests
import time

def get_player_urls(tournament_list):
    all_player_urls = []
    processed_tournaments = 0

    def process_tournament(tournament):
        nonlocal processed_tournaments

        try:
            # Get url of player list
            tournament_players_url = tournament + '/teams'

            # Get soup object
            soup = get_soup_object(tournament_players_url)

            # Check if page says "Access Denied"
            if 'Access Denied' in soup.text:
                print('Access Denied for tournament', tournament)
                time.sleep(600)  # Wait for 10 minutes
                return

            # Loop through links and add player link if not already added
            for player in soup.find_all('a', class_='list-group-item'):
                player_link = 'https://s5.sir.sportradar.com' + player['href']
                if player_link not in all_player_urls:
                    all_player_urls.append(player_link)

            processed_tournaments += 1
            if processed_tournaments % 200 == 0:
                print(f'{processed_tournaments} tournaments processed')

        except (requests.exceptions.ConnectionError, requests.exceptions.RequestException):
            # If there's an error, wait 30 seconds before trying again
            print('Exception on tournament', tournament)
            time.sleep(30)

    with concurrent.futures.ThreadPoolExecutor() as executor:
        # Submit tasks for each tournament
        futures = [executor.submit(process_tournament, tournament) for tournament in tournament_list]

        # Wait for all tasks to complete
        concurrent.futures.wait(futures)

    return all_player_urls

In [14]:
all_player_urls = get_player_urls(tournament_list)

200 tournaments processed
400 tournaments processed
600 tournaments processed
800 tournaments processed
1000 tournaments processed
1200 tournaments processed
1400 tournaments processed
1600 tournaments processed
1800 tournaments processed
2000 tournaments processed
2200 tournaments processed
2400 tournaments processed
2600 tournaments processed
2800 tournaments processed
3000 tournaments processed
3200 tournaments processed
3400 tournaments processed
3600 tournaments processed
3800 tournaments processed
4000 tournaments processed

We then run the following code to remove duplicated players:

In [22]:
unique_team_numbers = []
unique_team_urls = []

for i, url in enumerate(all_player_urls):
    team_number = int(url.split('/uniqueteam/')[1].split('/')[0])
    season_number = int(url.split('/season/')[1])
    
    if team_number not in unique_team_numbers:
        unique_team_numbers.append(team_number)
        unique_team_urls.append(url)
    
    # Print progress statement for every 10000 iterations
    if (i + 1) % 10000 == 0:
        print("Progress: {} iterations".format(i + 1))

Progress: 10000 iterations
Progress: 20000 iterations
Progress: 30000 iterations
Progress: 40000 iterations
Progress: 50000 iterations
Progress: 60000 iterations
Progress: 70000 iterations
Progress: 80000 iterations
Progress: 90000 iterations
Progress: 100000 iterations
Progress: 110000 iterations
Progress: 120000 iterations
Progress: 130000 iterations
Progress: 140000 iterations
Progress: 150000 iterations
Progress: 160000 iterations
Progress: 170000 iterations
Progress: 180000 iterations
Progress: 190000 iterations
Progress: 200000 iterations
Progress: 210000 iterations
Progress: 220000 iterations

In [27]:
unique_team_urls = pd.DataFrame(unique_team_urls)
unique_team_urls.to_csv('player_urls.csv', index=False)

In [7]:
all_player_urls = pd.read_csv('player_urls.csv')

In [8]:
all_player_urls = all_player_urls['0'].to_list()

In [9]:
def get_player_dataset(unique_player_urls):

    all_players_atts = []

    for i, player in enumerate(all_player_urls):
        
        try:
            
            # Get player attributes
            player_atts = get_player_atts(player)

            # Add to list
            all_players_atts.append(player_atts)

            if i % 1000 == 0:
                print(i, 'players added')
        except (requests.exceptions.ConnectionError, requests.exceptions.RequestException):
            # If there's an error, wait 30 seconds before trying again
            print('Exception on index', i)
            time.sleep(30)

    # Get column names
    column_names = all_players_atts[0].columns

    # Change list to 2D array
    all_players_atts = np.array(all_players_atts)
    all_players_atts = all_players_atts.reshape((all_players_atts.shape[0], all_players_atts.shape[-1]))

    # Create dataframe
    all_players_atts_df = pd.DataFrame(all_players_atts, columns=column_names)

    return all_players_atts_df

In [10]:
# Create dataset
all_players_atts_df = get_player_dataset(all_player_urls)

0 players added
1000 players added
2000 players added
3000 players added
Exception on tournament 3947
4000 players added
5000 players added
6000 players added
7000 players added
8000 players added
9000 players added
10000 players added
11000 players added
Exception on tournament 11384
12000 players added
13000 players added
14000 players added
15000 players added
16000 players added

In [11]:
# Save to file
all_players_atts_df.to_csv('player_df.csv', index=False)

## Creating a Dataset of Matches

First we load the tournament urls:

In [9]:
tournament_urls = pd.read_csv('tennis_tournament_urls.csv')['0'].tolist()

In [10]:
def get_country_list():

    import pycountry

    country_list = []
    
    countries = list(pycountry.countries)

    for country in countries:
        country_list.append(country.name)

    country_list.append('Czech Republic')
    
    return country_list

In [11]:
def get_tournament_atts(url):

    # Get soup object 
    soup = get_soup_object(url)

    # Get country list
    country_list = get_country_list()

    tournament_country = [country for country in country_list if country in soup.find('title').text]
    for row in soup.find_all('tr'):
        if 'Surface' in row.text:
            surface_row = row

    # Get attributes
    tournament_name = safe_extract(lambda: soup.title.text.split('-')[0].strip())
    tournament_country = safe_extract(lambda: tournament_country[0])
    surface = safe_extract(lambda: surface_row.find_all('td')[1].text)

    return tournament_name, tournament_country, surface

In [12]:
def get_match_df(tournament_url):

    # Set up Selenium to use a headless Chrome browser
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    driver = webdriver.Chrome(options=options)

    # Get tournament attributes
    tournament_name, tournament_country, surface = get_tournament_atts(tournament_url)

    # Load the web page with the table

    fixtures_url = tournament_url + '/fixtures/full'
    driver.get(fixtures_url)

    # Wait for the table to load by checking for a specific element on the page
    # that appears only after the table has been generated by JavaScript
    driver.implicitly_wait(10) 
    element = driver.find_elements('css selector', "#table-loaded")

    # Click the "show more" button if it's present
    try:
        show_more_button = driver.find_elements('xpath', '//*[@id="sr-container"]/div/div/div[4]/div/div/div/div/div[2]/div/div/div[2]/button')
        show_more_button[0].click()
        time.sleep(5) # wait for the new data to load
    except:
        pass

    driver.implicitly_wait(10) # wait for up to 10 seconds
    element = driver.find_elements('css selector', "#table-loaded")

    # Extract the HTML code of the entire page, including the dynamically generated table
    html = driver.page_source

    # Parse the HTML code using Beautiful Soup
    soup = BeautifulSoup(html, "html.parser")

    # Find the table using Beautiful Soup's find() or find_all() method
    table = soup.find("table")

    # Extract the data from the table as needed
    rows = table.find_all("tr")

    # Get match info
    match_dicts = []

    for row in rows:
        if '/' in row.text:
            date = row.find('td').text
            continue
        try:
            players = row.find_all('td')[1].text.split('-')
            both_players = [player[:-3] for player in players]
            home_player = both_players[0]
            away_player = both_players[1]

            scores_first = row.find_all('td')[2].text.split(':')
            scores_first = ':'.join([score[0] for score in scores_first][:2])
            scores_second = row.find_all('td')[3].text.split(':')
            scores_second = ':'.join([score[0] for score in scores_second][:2])
            scores_third = row.find_all('td')[4].text.split(':')
            scores_third = ':'.join([score[0] for score in scores_third][:2])
            scores_set = row.find_all('td')[5].text.split(':')
            scores_set = ':'.join([score[0] for score in scores_set][:2]) 

            match_dict = {
                'tournament_name': tournament_name,
                'tournament_country': tournament_country,
                'surface': surface,
                'date': date,
                'player1': home_player,
                'player2': away_player,
                'first_set': scores_first,
                'second_set': scores_second,
                'third_set': scores_third,
                'match_result': scores_set
            }

            match_dicts.append(match_dict)
                
        except:
            continue

    # Close the headless browser
    driver.quit()

    # Create a dataframe
    match_df = pd.DataFrame(match_dicts)

    return match_df

In [13]:
def get_matches_df(tournament_urls):

    # Create empty list
    tournament_match_dfs = []

    # Get matches for each tournament and add to list
    for i, tournament in enumerate(tournament_urls):
        try:
            matches_df = get_match_df(tournament)
            tournament_match_dfs.append(matches_df)
        except:
            print('Error on url:', tournament)
            continue

        if i % 25 == 0:
            print(i, 'tournaments added') 

    # Create dataframe
    matches_df = pd.concat(tournament_match_dfs)
    matches_df = matches_df.reset_index(drop=True)

    return matches_df

In [14]:
# Create dataset
all_matches_df = get_matches_df(tournament_urls)

0 tournaments added
25 tournaments added
50 tournaments added
75 tournaments added
100 tournaments added
125 tournaments added
150 tournaments added
175 tournaments added
200 tournaments added
225 tournaments added
250 tournaments added
275 tournaments added
300 tournaments added
325 tournaments added
350 tournaments added
375 tournaments added
400 tournaments added
425 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73419
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73425
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73429
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73433
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73437
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73449
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73453
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73457
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73461
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73475
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73479
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73495
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73493
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73497
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73491
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73503
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73511
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73519
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73525
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73529
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73531
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73541
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73537
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73545
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73557
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73561
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73575
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73579
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73585
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73595
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73599
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73617
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73621
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73625
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73629
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73633
500 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73837
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73841
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73845
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73851
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73849
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73859
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73867
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73887
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73883
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73891
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73895
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73893
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73905
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73903
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73909
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73921
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73927
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73923
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73931
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73935
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73939
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73947
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73951
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73955
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73961
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73963
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73973
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73975
550 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/73997
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74003
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74009
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74013
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74029
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74033
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74043
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74047
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74051
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74053
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74061
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74065
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74075
575 tournaments added
600 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/74281
625 tournaments added
650 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75235
675 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75359
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75363
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75371
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75375
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75383
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75391
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75397
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75395
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75409
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75417
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75421
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75429
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75433
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75437
700 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75445
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75451
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75455
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75459
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75463
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75467
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75471
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75475
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75479
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75483
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75489
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75493
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75497
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75505
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75507
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75511
725 tournaments added
750 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75767
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75769
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75773
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75783
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75787
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75791
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75795
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75799
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/75803
775 tournaments added
800 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/76255
825 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/76507
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/76581
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/76677
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/77031
850 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/77767
875 tournaments added
900 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/78735
925 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/79119
950 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/79471
975 tournaments added
1000 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80100
1025 tournaments added
1050 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80536
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80542
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80546
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80552
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80564
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80612
1075 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80760
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80766
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80770
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80774
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80780
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80800
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80860
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80876
1125 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80904
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80916
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80920
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/80924
1150 tournaments added
1175 tournaments added
1200 tournaments added
1225 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/82000
1250 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/82364
1275 tournaments added
1300 tournaments added
1325 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/82820
1350 tournaments added
1375 tournaments added
1400 tournaments added
1425 tournaments added
1450 tournaments added
1475 tournaments added
1500 tournaments added
1525 tournaments added
1550 tournaments added
1575 tournaments added
1600 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/85752
1650 tournaments added
1675 tournaments added
1700 tournaments added
1725 tournaments added
1750 tournaments added
1775 tournaments added
1800 tournaments added
1825 tournaments added
1850 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/87956
1875 tournaments added
1900 tournaments added
1925 tournaments added
1950 tournaments added
1975 tournaments added
2000 tournaments added
2025 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/89129
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/89201
2050 tournaments added
2075 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/89433
2100 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/89843
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/89847
2125 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/90125
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/90133
2150 tournaments added
2175 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/90457
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/90481
2200 tournaments added
2225 tournaments added
2250 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/91179
2275 tournaments added
2300 tournaments added
2325 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/91549
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/91559
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/91563
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/91571
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/91579
2350 tournaments added
2375 tournaments added
2400 tournaments added
2425 tournaments added
2450 tournaments added
2475 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/92541
2500 tournaments added
2525 tournaments added
2550 tournaments added
2575 tournaments added
2600 tournaments added
2625 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/93479
2650 tournaments added
2675 tournaments added
2700 tournaments added
2725 tournaments added
2750 tournaments added
2775 tournaments added
2800 tournaments added
2825 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/95143
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/95307
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/95309
2850 tournaments added
2875 tournaments added
2900 tournaments added
2925 tournaments added
2950 tournaments added
2975 tournaments added
3000 tournaments added
3025 tournaments added
3050 tournaments added
3075 tournaments added
3100 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/97747
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/97749
3125 tournaments added
3150 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/97997
3175 tournaments added
3200 tournaments added
3225 tournaments added
3250 tournaments added
3275 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99005
3300 tournaments added
3325 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99295
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99299
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99361
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99363
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99357
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99367
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99371
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99375
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99383
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99397
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99395
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99401
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99421
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99425
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99429
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99435
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99439
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99443
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99449
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99459
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99463
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99467
3375 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99649
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99661
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99657
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99663
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99673
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99677
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99681
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99687
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99693
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99697
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99703
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99707
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99711
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99715
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99819
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99825
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99829
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99833
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99837
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99859
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99867
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99899
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99903
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99909
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99913
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99919
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99923
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99927
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99931
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99935
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99953
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99961
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/99965
3450 tournaments added
3475 tournaments added
3500 tournaments added
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/100495
Error on url: https://s5.sir.sportradar.com/sportradar/en/5/season/100499

In [ ]:
# Save to file
all_matches_df.to_csv('matches_df.csv', index=False)

# Data Cleaning

In [3]:
import pandas as pd

In [4]:
# Load the datasets
players_df = pd.read_csv('player_df.csv')
matches_df = pd.read_csv('matches_df.csv')

First we can remove any duplicates:

In [5]:
print('Old number of player entries:', players_df.shape[0])
print('Old number of match entries:', matches_df.shape[0])

# Remove duplicates
players_df = players_df.drop_duplicates()
matches_df = matches_df.drop_duplicates()

print('\n')
print('New number of player entries:', players_df.shape[0])
print('New number of match entries:', matches_df.shape[0])

Old number of player entries: 16647
Old number of match entries: 216226


New number of player entries: 16647
New number of match entries: 216225

We can then drop all duplicated names in players_df, but making sure to only drop entries with the fewest NaN values:

In [6]:
print('Old number of player entries:', players_df.shape[0])

# Count the number of NaN values for each row
players_df['num_nans'] = players_df.isnull().sum(axis=1)

# Drop duplicated rows based on the 'name' column and keep the row with the fewest NaN values
players_df = players_df.sort_values(['name', 'num_nans']).drop_duplicates(subset='name', keep='last')

# Drop the 'num_nans' column
players_df = players_df.drop('num_nans', axis=1)

print('New number of player entries:', players_df.shape[0])

Old number of player entries: 16647
New number of player entries: 16548

Next we'll drop all entries for matches_df where we don't have the match result:

In [7]:
print('Old number of match entries:', matches_df.shape[0])

# Drop rows
matches_df = matches_df[matches_df.match_result != '-']

print('New number of match entries:', matches_df.shape[0])

Old number of match entries: 216225
New number of match entries: 214458

We'll also drop any values where the name for either player is missing:

In [8]:
print('Old number of match entries:', matches_df.shape[0])

# Drop all rows where player1 or player2 is NaN
matches_df = matches_df.dropna(subset=['player1', 'player2'])

print('New number of match entries:', matches_df.shape[0])

Old number of match entries: 214458
New number of match entries: 214089

Next we will replace all NaN values for country with the correct country:

In [9]:
# Get a list of tournament names where the country is missing
matches_df[matches_df.tournament_country.isna()]['tournament_name'].unique()

array(['2019 ATP Challenger Banja Luka, Bosnia & Herzegovina Men Singles',
       '2019 ATP Challenger Charlottesville, USA Men Singles',
       '2019 ATP Challenger Glasgow, Great Britain Men Singles',
       '2019 ATP Challenger Cary, USA Men Singles',
       '2019 ATP Challenger Columbus III, USA Men Singles',
       '2019 ATP Challenger Fairfield, USA Men Singles',
       '2019 ATP Challenger New Haven, USA Men Singles',
       '2019 ATP Challenger Kaohsiung, Chinese Taipei Men Singles',
       '2019 ATP Challenger Las Vegas, USA Men Singles',
       '2019 ATP Challenger Tiburon, USA Men Singles',
       '2019 ITF Russia F4, Men Singles',
       '2019 ITF Russia 07A, Women Singles',
       '2019 ITF South Korea 07A, Women Singles',
       '2019 ITF Russia 08A, Women Singles',
       '2019 ITF South Korea 08A, Women Singles',
       '2019 ITF USA F27, Men Singles', '2019 ITF USA 34A, Women Singles',
       '2019 ITF USA 30A, Women Singles', 'US Open Women Singles 2020',
       'US Open Men Singles 2020', '2019 ITF USA 35A, Women Singles',
       '2019 ITF Great Britain 01B, Women Singles',
       '2019 ITF USA F28, Men Singles', '2019 ITF USA F29, Men Singles',
       '2019 ITF USA F30, Men Singles',
       '2019 ITF Great Britain F7, Men Singles',
       '2019 ITF Great Britain 01C, Women Singles',
       '2019 ITF USA 32A, Women Singles', '2019 ITF USA F39, Men Singles',
       '2019 ITF Vietnam F1, Men Singles',
       '2019 ITF USA 44A, Women Singles',
       '2019 ITF USA 47A, Women Singles', '2019 ITF USA F6B, Men Singles',
       '2019 ITF Vietnam F2, Men Singles',
       '2019 ITF USA 48A, Women Singles',
       '2019 ITF USA 39A, Women Singles',
       '2019 ITF South Korea F5, Men Singles',
       '2019 ITF USA F41, Men Singles', '2019 ITF USA 40A, Women Singles',
       '2019 ITF USA 49A, Women Singles', '2019 ITF USA F32, Men Singles',
       '2019 ITF USA F42, Men Singles', '2019 ITF USA 38B, Women Singles',
       '2019 ITF USA 50A, Women Singles',
       '2019 ITF USA 41A, Women Singles',
       '2019 ITF USA 42A, Women Singles', '2019 ITF USA F33, Men Singles',
       '2019 ATP Challenger Houston, USA Men Singles',
       '2019 ATP Challenger Knoxville, USA Men Singles',
       '2019 ITF USA 51A, Women Singles', '2019 ITF USA F43, Men Singles',
       '2019 ITF USA 43A, Women Singles',
       '2019 ITF USA F38B, Men Singles',
       '2019 ITF USA 47B, Women Singles', '2019 ITF USA F35, Men Singles',
       '2019 ITF USA F40, Men Singles', '2019 ITF USA F36, Men Singles',
       '2019 ITF USA 48B, Women Singles',
       '2019 ITF USA 46A, Women Singles',
       '2020 ATP Challenger Newport Beach, USA Men Singles',
       '2020 WTA 125K Newport Beach, USA Women Singles',
       '2020 ATP Challenger Ann Arbor, USA Men Singles',
       '2020 WTA New York, USA Women Singles',
       '2020 WTA Dubai, UAE Women Singles',
       '2020 WTA St. Petersburg, Russia Women Singles',
       '2019 ITF USA F37, Men Singles', '2019 ITF USA 52A, Women Singles',
       '2020 ATP Delray Beach, USA Men Singles',
       '2020 ATP New York, USA Men Singles',
       '2020 ATP Dubai, UAE Men Singles',
       '2020 ATP St. Petersburg, Russia Men Singles',
       '2021 Olympic Tournament Mixed Double',
       '2020 ATP Challenger Columbus, USA Men Singles',
       '2020 ATP Challenger Cleveland, USA Men Singles',
       '2020 ATP Challenger Dallas, USA Men Singles',
       '2019 Czech Tennis Extraliga Men Singles',
       '2019 Czech Tennis Extraliga Women Singles',
       '2019 World Tennis Championship Men Singles',
       '2019 Exhibition Hawaii Open Men Singles',
       '2019 Exhibition Diriyah Tennis Cup Men Singles', 'Fed Cup 2020',
       '2020 ITF USA F1, Men Singles', '2020 ITF USA F2, Men Singles',
       '2020 ITF USA 01A, Women Singles',
       '2020 ITF USA 02A, Women Singles',
       '2020 Exhibition Kooyong Classic Men Singles',
       '2020 Exhibition Kooyong Classic Women Singles',
       '2020 ITF Russia F1, Men Singles',
       '2020 ITF Russia 02A, Women Singles',
       '2020 ITF USA 03A, Women Singles', '2020 ITF USA F4, Men Singles',
       '2020 ITF USA F5, Men Singles', '2020 ITF USA 04A, Women Singles',
       '2020 ITF Great Britain F1, Men Singles',
       '2020 ITF USA F6, Men Singles', '2020 ITF USA 05A, Women Singles',
       '2020 ITF Great Britain F2, Men Singles',
       '2020 ITF Great Britain 01A, Women Singles',
       '2020 ITF Great Britain F3, Men Singles',
       '2020 ITF USA 07A, Women Singles',
       '2020 ITF Russia 01A, Women Singles',
       '2020 ITF Great Britain 03A, Women Singles',
       '2020 ITF USA F7, Men Singles', '2020 ITF USA 08A, Women Singles',
       '2020 ITF Russia F2, Men Singles',
       '2020 ITF Russia 03A, Women Singles', 'Wimbledon Men Singles 2021',
       'Wimbledon Women Singles 2021', 'Wimbledon Mixed Double 2021',
       '2020 UTR Pro Match Series Men Singles', 'Exo', 'Exhibition Exo',
       'Wimbledon Men Singles 2022', '2020 LiveScore Cup Women Singles',
       '2020 WTA Lexington, USA Women Singles',
       'Wheelchairs US Open, New York, USA Men Singles 2020',
       'Wheelchairs US Open, New York, USA Women Singles 2020',
       'US Open Men Singles 2021', 'US Open Women Singles 2021',
       '2020 ATP Challenger Cary, USA Men Singles',
       '2020 ITF USA 40A, Women Singles', '2021 French Open, Singles',
       '2021 French Open Women Singles',
       '2020 ITF USA 42A, Women Singles',
       '2020 ATP Challenger Orlando, USA Men Singles',
       '2020 ITF USA F37, Men Singles', '2020 ITF USA 48A, Women Singles',
       '2020 Czech Tennis Extraliga Men Singles',
       '2020 Czech Tennis Extraliga Women Singles',
       '2021 ATP Delray Beach, USA Men Singles',
       '2021 WTA Abu Dhabi, UAE Women Singles',
       '2021 ATP Dubai, UAE Men Singles',
       '2021 ATP Miami, USA Men Singles',
       '2021 Exhibition Laver Cup Men Singles',
       '2021 ATP London, Great Britain, Singles',
       '2021 ATP Eastbourne, Great Britain, Singles',
       '2021 ATP Newport, USA Men Singles',
       '2021 Olympic Tournament Men Singles',
       '2021 ATP Atlanta, USA Men Singles',
       '2021 ATP Washington, USA, Singles',
       '2021 ATP Cincinnati, USA, Singles',
       '2021 ATP Winston Salem, USA, Singles',
       '2021 ATP St. Petersburg, Russia Men Singles',
       '2021 ATP Moscow, Russia, Singles',
       '2021 WTA Dubai, UAE Women Singles',
       '2021 WTA St. Petersburg, Russia Women Singles',
       '2021 WTA Charleston, USA Women Singles',
       '2021 WTA Miami, USA Women Singles',
       '2021 WTA Nottingham, Great Britain Women Singles',
       '2021 WTA Birmingham, Great Britain Women Singles',
       '2021 WTA Bad Homburg Women Singles',
       '2021 WTA Eastbourne, Great Britain Women Singles',
       '2021 ITF USA 01A, Women Singles',
       '2021 ITF Russia F1, Men Singles',
       '2021 ATP Challenger St Petersburg, Russia Men Singles',
       '2021 ATP Challenger St Petersburg 2, Russia Men Singles',
       '2021 ATP Challenger Cleveland, USA Men Singles',
       '2021 ITF Russia F2, Men Singles', '2021 ITF USA F1, Men Singles',
       '2021 ITF USA 02A, Women Singles',
       '2021 ITF Russia 01A, Women Singles',
       '2021 ITF USA 03A, Women Singles',
       '2021 ITF USA 04A, Women Singles',
       '2021 ATP Challenger Orlando, USA Men Singles',
       '2021 ITF Russia F5, Men Singles',
       '2021 ITF Russia 02A, Women Singles',
       '2021 ATP Challenger Tallahassee, USA Men Singles',
       '2021 WTA Charleston 2, USA Women Singles',
       '2021 ITF Russia F3, Men Singles',
       '2021 ITF Russia F4, Men Singles',
       '2021 ATP Challenger Zagreb Men Singles',
       '2021 WTA 125K Charleston, USA Women Singles',
       '2021 WTA San Jose, USA Women Singles',
       '2021 WTA Cincinnati, USA Women Singles',
       '2021 WTA 125K Chicago, USA Women Singles',
       '2021 WTA Cleveland, USA Women Singles',
       '2021 ITF USA 07A, Women Singles',
       '2021 ITF USA 08A, Women Singles',
       '2021 ITF USA 09A, Women Singles',
       '2021 ATP Challenger Little Rock, USA Men Singles',
       '2021 ITF USA 10A, Women Singles',
       '2021 ITF Bosnia & Herzegovina F4, Men Singles',
       '2021 ATP Challenger Nottingham, Great Britain Men Singles',
       '2021 ATP Challenger Orlando 2, USA Men Singles',
       '2021 ATP Challenger Nottingham 2, Great Britain Men Singles',
       '2021 ITF Bosnia & Herzegovina F1, Men Singles',
       '2021 ITF USA F3, Men Singles', '2021 ITF USA 12A, Women Singles',
       '2021 ITF Bosnia & Herzegovina F2, Men Singles',
       '2021 ITF Macedonia F1, Men Singles',
       '2021 ITF Bosnia & Herzegovina 01A, Women Singles',
       '2021 ITF Russia 03A, Women Singles',
       '2021 WTA 125K Concord, USA Women Singles',
       '2021 ITF USA F8, Men Singles', '2021 ITF USA F6, Men Singles',
       '2021 ITF Great Britain 01A, Women Singles',
       '2021 ITF USA 14A, Women Singles',
       '2021 ATP Challenger Cary, USA Men Singles',
       '2021 ATP Challenger Lexington, USA Men Singles',
       '2021 ITF USA F7, Men Singles', '2021 ITF USA 13A, Women Singles',
       'Juniors Wimbledon, London, GB Men Singles 2021',
       'Juniors Wimbledon, London, GB Women Singles 2021',
       'Wheelchairs Wimbledon, London, GB Men Singles 2021',
       'Wheelchairs Wimbledon, London, GB Women Singles 2021',
       'French Open Women Singles 2022', 'French Open Men Singles 2022',
       '2021 ITF USA F5, Men Singles',
       '2021 WTA Chicago, USA Women Singles',
       '2021 ITF Bosnia & Herzegovina F5, Men Singles',
       '2021 ITF USA F9, Men Singles', '2021 ITF USA F10, Men Singles',
       '2021 ATP Challenger Banja Luka, Bosnia & Herzegovina Men Singles',
       '2021 ATP Challenger Cary II, USA Men Singles',
       '2021 WTA Chicago 2, USA Women Singles',
       '2021 WTA Moscow, Russia Women Singles',
       'Wheelchairs US Open, New York, USA Men Singles 2021',
       'Wheelchairs US Open, New York, USA Women Singles 2021',
       '2021 ITF USA 16A, Women Singles',
       '2021 ATP San Diego, USA Men Singles',
       '2021 ATP Challenger Columbus, USA Men Singles',
       '2021 WTA 125 Midland, USA Women Singles',
       'Juniors US Open, New York, USA Men Singles 2021',
       'Juniors US Open, New York, USA Women Singles 2021',
       '2021 ITF USA F13, Men Singles',
       'WTA 125K Columbus, USA Women Singles 2021',
       'ITF USA F14, Men Singles 2021', 'ITF USA 17A, Women Singles 2021',
       'US Open Men Singles 2022', 'US Open Women Singles 2022',
       'ITF USA F15, Men Singles 2021', 'ITF USA 19A, Women Singles 2021',
       'ITF USA F16, Men Singles 2021', 'ITF USA F21, Men Singles 2021',
       'ITF USA 20A, Women Singles 2021',
       'ITF USA 22A, Women Singles 2021',
       'ITF USA 21A, Women Singles 2021',
       'ATP Challenger Las Vegas , USA Men Singles 2021',
       'ATP Challenger Charlottesville, USA Men Singles 2021',
       'ATP Challenger Knoxville, USA Men Singles 2021',
       'ITF Russia F6, Men Singles 2021', 'ITF USA F22, Men Singles 2021',
       'ITF USA 23A, Women Singles 2021',
       'ITF USA 24A, Women Singles 2021',
       'ITF USA 25A, Women Singles 2021',
       'ITF Russia 05A, Women Singles 2021',
       'ATP Challenger Champaign, USA Men Singles 2021',
       'ITF USA F17, Men Singles 2021', 'ITF USA 26A, Women Singles 2021',
       'ITF USA 28A, Women Singles 2021',
       'ITF USA 29A, Women Singles 2021', 'ITF USA F19, Men Singles 2021',
       'ITF USA F20, Men Singles 2021', 'ITF USA F23, Men Singles 2021',
       'USA F24 Men Singles 2021', 'ITF USA 30A, Women Singles 2021',
       'ITF USA F25, Men Singles 2021', 'ITF USA 31A, Women Singles 2021',
       'ITF USA F26, Men Singles 2021', 'ITF USA F27, Men Singles 2021',
       'ITF USA F28B, Men Singles 2021',
       'ITF Bolivia F1, Men Singles 2021',
       'ITF USA 32A, Women Singles 2021',
       'ITF Russia F7, Men Singles 2021',
       'ITF Russia 06A, Women Singles 2021',
       'ATP Dubai, UAE Men Singles 2022',
       'ATP Miami, USA Men Singles 2022',
       'ATP Houston, USA Men Singles 2022',
       'ATP London, Great Britain Men Singles 2022',
       'ATP Eastbourne, Great Britain Men Singles 2022',
       'ATP Dallas, USA Men Singles 2022', 'Wimbledon Mixed Double 2022',
       'WTA St. Petersburg, Russia Women Singles 2022',
       'WTA Dubai, UAE Women Singles 2022',
       'WTA Miami, USA Women Singles 2022',
       'WTA Charleston, USA Women Singles 2022',
       'WTA Nottingham, Great Britain Women Singles 2022',
       'WTA Birmingham, Great Britain Women Singles 2022',
       'WTA Eastbourne, Great Britain Women Singles 2022',
       'WTA Bad Homburg Women Singles 2022',
       'WTA 125K Seoul, Korea Republic, Women Singles 2021',
       'World Tennis Championship Men Singles 2021',
       'World Tennis Championship Women Singles 2021',
       'ATP Challenger Columbus, USA Men Singles 2022',
       'ATP Challenger Santa Cruz, Bolivia Men Singles 2022',
       'ATP Challenger Cleveland, USA Men Singles 2022',
       'ITF Great Britain F2, Men Singles 2022',
       'ITF USA 02A, Women Singles 2022',
       'ITF Great Britain 01A, Women Singles 2022',
       'ITF Russia F1, Men Singles 2022',
       'ITF Russia 01A, Women Singles 2022',
       'ITF USA F1, Men Singles 2022',
       'ITF Great Britain F3, Men Singles 2022',
       'ITF USA 03A, Women Singles 2022',
       'ITF Great Britain 02A, Women Singles 2022',
       'ATP Challenger Phoenix, USA Men Singles 2022',
       'ATP Challenger Santa Cruz 2, Bolivia Men Singles 2022',
       'ITF USA 04A, Women Singles 2022',
       'ITF Great Britain F4, Men Singles 2022',
       'ITF USA F2, Men Singles 2022',
       'ITF Great Britain 04A, Women Singles 2022',
       'ATP Challenger Sarasota, USA Men Singles 2022',
       'ITF Great Britain F1, Men Singles 2022',
       'ITF USA F3, Men Singles 2022',
       'ITF Great Britain 03A, Women Singles 2022',
       'ITF USA F4, Men Singles 2022',
       'ATP Challenger Tallahassee, USA Men Singles 2022',
       'ATP Challenger Savannah, USA Men Singles 2022',
       'ITF USA 06A, Women Singles 2022',
       'ATP Newport, USA Men Singles 2022',
       'ATP Atlanta, USA Men Singles 2022',
       'ATP Washington, USA Men Singles 2022',
       'ATP Cincinnati, USA Men Singles 2022',
       'ATP Winston Salem, USA Men Singles 2022',
       'WTA San Jose, USA Women Singles 2022',
       'WTA Cleveland, USA Women Singles 2022',
       'WTA Cincinnati, USA Women Singles 2022',
       'Challenge Zagreb Men Singles 2022',
       'ITF USA F5, Men Singles 2022',
       'Juniors US Open, New York, USA Men Singles 2022',
       'Juniors US Open, New York, USA Women Singles 2022',
       'ITF USA F6, Men Singles 2022',
       'Exhibition Laver Cup Men Singles 2022',
       'WTA 125K Concord, USA Women Singles 2022',
       'ATP Challenger Surbiton, Great Britain Men Singles 2022',
       'ATP Challenger Little Rock, USA Men Singles 2022',
       'ATP Challenger Orlando, USA Men Singles 2022',
       'ATP Challenger Nottingham, Great Britain Men Singles 2022',
       'ATP Challenger Ilkley, Great Britain Men Singles 2022',
       'ITF Great Britain F5, Men Singles 2022',
       'ITF USA F7, Men Singles 2022', 'ITF USA 09A, Women Singles 2022',
       'ITF Great Britain 07A, Women Singles 2022',
       'WTA 125 Midland, USA Women Singles 2022',
       'ITF Great Britain F6, Men Singles 2022',
       'ITF USA F8, Men Singles 2022', 'ITF USA 10A, Women Singles 2022',
       'ITF USA 11A, Women Singles 2022',
       'ITF Great Britain 06A, Women Singles 2022',
       'ITF USA 12A, Women Singles 2022', 'ITF USA F9, Men Singles 2022',
       'ITF USA 13A, Women Singles 2022',
       'ITF Great Britain 08A, Women Singles 2022',
       'ITF Great Britain F7, Men Singles 2022',
       'ITF USA 14A, Women Singles 2022',
       'ITF Great Britain F8, Men Singles 2022',
       'ITF Bosnia & Herzegovina F1, Men Singles 2022',
       'ITF USA 15A, Women Singles 2022',
       'ITF Great Britain 05A, Women Singles 2022',
       'ITF USA 16A, Women Singles 2022',
       'ITF USA 26A, Women Singles 2022',
       'ITF Bosnia & Herzegovina F2, Men Singles 2022',
       'ITF Bosnia & Herzegovina F3, Men Singles 2022',
       'ITF USA 17A, Women Singles 2022',
       'ATP Challenger Rome, USA Men Singles 2022',
       'San Diego, USA Women Singles 2022',
       'ITF Great Britain 09A, Women Singles 2022',
       'ITF USA F11, Men Singles 2022',
       'ITF Vietnam F1, Men Singles 2022',
       'ITF Bosnia & Herzegovina F4, Men Singles 2022',
       'ITF USA 18A, Women Singles 2022',
       'ITF South Korea 01A, Women Singles 2022',
       'ITF USA F12, Men Singles 2022', 'ITF USA F13, Men Singles 2022',
       'Bosnia & Herzegovina F5, Men Singles 2022',
       'ITF Vietnam F2, Men Singles 2022',
       'ITF South Korea 04A, Women Singles 2022',
       'ITF USA 19A, Women Singles 2022',
       'ITF Bosnia & Herzegovina 01A, Women Singles 2022',
       'WTA Washington, USA Women Singles 2022',
       'ITF USA F14, Men Singles 2022',
       'ITF Vietnam F3, Men Singles 2022',
       'ITF Great Britain 10A, Women Singles 2022',
       'ITF USA 20A, Women Singles 2022',
       'ITF USA 21A, Women Singles 2022',
       'ATP Challenger Lexington, USA Men Singles 2022',
       'ITF USA 22A, Women Singles 2022', 'ITF USA F16, Men Singles 2022',
       'ITF USA F17, Men Singles 2022', 'ITF USA 23A, Women Singles 2022',
       'ITF USA F18, Men Singles 2022', 'ITF USA 24A, Women Singles 2022',
       'ITF USA F19, Men Singles 2022', 'ITF USA 27A, Women Singles 2022',
       'ITF USA 25A, Women Singles 2022',
       'ITF USA 28A, Women Singles 2022', 'ITF USA F20, Men Singles 2022',
       'ITF USA F21, Men Singles 2022',
       'Wheelchairs Wimbledon, London, GB Men Singles 2022',
       'Juniors Wimbledon, London, GB Men Singles 2022',
       'Juniors Wimbledon, London, GB Women Singles 2022',
       'Wheelchairs US Open, New York, USA Men Singles 2022',
       'Wheelchairs US Open, New York, USA Women Singles 2022',
       'Wheelchairs Juniors US Open, New York, USA Women Singles 2022',
       'ITF Great Britain F13, Men Singles 2022',
       'ITF USA F22, Men Singles 2022', 'ITF USA F23, Men Singles 2022',
       'ITF Great Britain 14A, Women Singles 2022',
       'ITF USA 30A, Women Singles 2022',
       'ATP Challenger Chicago, USA Men Singles 2022',
       'USA F24 Men Singles 2022', 'ITF USA 31A, Women Singles 2022',
       'ITF Great Britain F11, Men Singles 2022',
       'ITF USA F25, Men Singles 2022', 'ITF USA 32A, Women Singles 2022',
       'ITF Great Britain 15A, Women Singles 2022',
       'ATP Challenger Cary, USA Men Singles 2022',
       'ATP Challenger Columbus II, USA Men Singles 2022',
       'ATP Challenger Buenos Aires II, ARG Men Singles 2022',
       'ATP Challenger Charleston, SC, USA Men Singles 2022',
       'ATP San Diego, USA Men Singles 2022',
       'ATP Seoul, Korea Republic Men Singles 2022',
       'ITF USA F26, Men Singles 2022',
       'ITF Great Britain F10, Men Singles 2022',
       'ITF USA 35A, Women Singles 2022',
       'ITF Great Britain 12A, Women Singles 2022',
       'ITF USA F27, Men Singles 2022', 'ITF USA 37A, Women Singles 2022',
       'ITF Great Britain F14, Men Singles 2022',
       'ITF Korea F2, Men Singles 2022', 'ITF USA F28B, Men Singles 2022',
       'ITF USA 36A, Women Singles 2022',
       'ITF Great Britain 16A, Women Singles 2022',
       'ATP Challenger Gwangju, Korea Republic Men Singles 2022',
       'ATP Challenger Tiburon, USA Men Singles 2022',
       'ATP Challenger Seoul, Korea Republic Men Singles 2022',
       'ATP Challenger Fairfield, USA Men Singles 2022',
       'ATP Challenger Charlottesville, USA Men Singles 2022',
       'ATP Challenger Las Vegas , USA Men Singles 2022',
       'ATP Challenger Busan, Korea Republic Men Singles 2022',

In [10]:
# Create a dictionary to map tournament names to countries
tournament_countries = {'Adelaide': 'Australia',
                        'Seoul': 'South Korea',
                        'Maracay': 'Venezuela', 
                        'Maracaibo': 'Venezuela',
                        'Las Vegas': 'USA',
                        'Eastbourne': 'Great Britain',
                        'Surbiton': 'Great Britain',
                        'Korea': 'South Korea',
                        'Delray': 'USA',
                        'Chinese Taipei': 'Taiwan',
                        'UAE': 'United Arab Emirates',
                        'Lexington': 'USA',
                        'Bosnia & Herzegovina': 'Bosnia & Herzegovina',
                        'French': 'France',
                        'USA': 'USA',
                        'Russia': 'Russia',
                        'Great Britain': 'Great Britain',
                        'Macedonia': 'North Macedonia',
                        'US': 'USA',
                        'Wimbledon': 'Great Britain',
                        'Czech': 'Czech Republic',
                        'Vietnam': 'Vietnam',
                        'Movistar': 'Chile'
                        }

# Define a function to apply to each row of the dataframe
def update_tournament_country(row):
    for tournament_name in tournament_countries.keys():
        if tournament_name in row['tournament_name']:
            return tournament_countries[tournament_name]
    return row['tournament_country']

# Apply the function to each row of the dataframe
matches_df['tournament_country'] = matches_df.apply(update_tournament_country, axis=1)

In [11]:
# Check new number of NaN values
print('Number of NaN values in tournament country:', matches_df.tournament_country.isna().sum())

Number of NaN values in tournament country: 1394

Finally we'll replace all NaN values in the Surface column with Unknown:

In [12]:
matches_df['surface'] = matches_df['surface'].fillna('Unknown')

We can now check that we have no more NaN values:

In [13]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 214089 entries, 0 to 216214
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tournament_name     214089 non-null  object
 1   tournament_country  212695 non-null  object
 2   surface             214089 non-null  object
 3   date                214089 non-null  object
 4   player1             214089 non-null  object
 5   player2             214089 non-null  object
 6   first_set           214089 non-null  object
 7   second_set          214089 non-null  object
 8   third_set           214089 non-null  object
 9   match_result        214089 non-null  object
dtypes: object(10)
memory usage: 18.0+ MB

Next we will look into the values for surface to ensure they are consistent for both datasets:

In [14]:
print('matches_df surface values:')
print(matches_df.surface.value_counts())
print('\n')
print('players_df fav_surface values:')
print(players_df.fav_surface.value_counts())

matches_df surface values:
surface
Clay                 96109
Hardcourt outdoor    91099
Hardcourt indoor     20825
Grass                 2745
Carpet indoor         1430
Synthetic outdoor     1108
Unknown                644
Synthetic grass         81
Synthetic indoor        48
Name: count, dtype: int64


players_df fav_surface values:
fav_surface
Hard             3446
Clay             2380
Grass             265
Carpet indoor      94
Name: count, dtype: int64

We can see that there are some inconsistities here so we will ammend these:

In [15]:
matches_df['surface'] = matches_df['surface'].replace({
        'Hardcourt outdoor': 'Hard',
        'Hardcourt indoor': 'Hard',
        'Synthetic outdoor': 'Unknown',
        'Synthetic indoor': 'Carpet indoor'
    })

In [16]:
print('matches_df surface values:')
print(matches_df.surface.value_counts())
print('\n')
print('players_df fav_surface values:')
print(players_df.fav_surface.value_counts())

matches_df surface values:
surface
Hard               111924
Clay                96109
Grass                2745
Unknown              1752
Carpet indoor        1478
Synthetic grass        81
Name: count, dtype: int64


players_df fav_surface values:
fav_surface
Hard             3446
Clay             2380
Grass             265
Carpet indoor      94
Name: count, dtype: int64

Next we can convert our date column into a datetime format:

In [17]:
from datetime import datetime

# Create a function to convert strings to datetime
def convert_to_date(date_str):
    return datetime.strptime(date_str, '%d/%m/%y').date()

In [18]:
# Apply function to date column on matches_df
matches_df['date'] =matches_df['date'].apply(convert_to_date)

In [19]:
matches_df

,tournament_name,tournament_country,surface,date,player1,player2,first_set,second_set,third_set,match_result
0,"2019 ITF Kenya 04A, Women Singles",Kenya,Hard,2019-08-12,"Asumwa, Roselida","Wachira, Mary",6:1,6:2,-,2:0
1,"2019 ITF Kenya 04A, Women Singles",Kenya,Hard,2019-08-12,"Gadhia, Shania Kaur","Wanjala, Cynthia",4:6,2:6,-,0:2
2,"2019 ITF Kenya 04A, Women Singles",Kenya,Hard,2019-08-12,"Gowda, Vibhasree","Owegi, Alicia",1:6,0:6,-,0:2
3,"2019 ITF Kenya 04A, Women Singles",Kenya,Hard,2019-08-13,"Codino, Fiona","Tran, Demi",6:2,6:4,-,2:0
4,"2019 ITF Kenya 04A, Women Singles",Kenya,Hard,2019-08-13,"Rajmohan, Nidhitra","Stevens, Lexie",1:6,0:6,-,0:2
...,...,...,...,...,...,...,...,...,...,...
216210,"ITF Serbia 06A, Women Singles 2023",Serbia,Clay,2023-05-22,"Alibalic, Nina","Stankovic, Anja",4:6,6:0,6:1,1:2
216211,"ITF Serbia 06A, Women Singles 2023",Serbia,Clay,2023-05-22,"Rasskovskaia, Lidiia","Suslova, Sofiia",6:4,6:0,-,2:0
216212,"ITF Serbia 06A, Women Singles 2023",Serbia,Clay,2023-05-22,"Cibulskyte, Mile","Zhang, Ruien",0:6,1:6,-,0:2
216213,"ITF Serbia 06A, Women Singles 2023",Serbia,Clay,2023-05-22,"Jankovic, Iva","Gemovic, Elena",4:6,4:6,-,0:2
216214,"ITF Serbia 06A, Women Singles 2023",Serbia,Clay,2023-05-22,"Tiron, Evelyne Christelle Atticia","Samardzic, Svetlana",6:4,6:2,-,2:0

In [20]:
tournament_urls[-30:]

NameError: name 'tournament_urls' is not defined

In [ ]:
import concurrent.futures

def check_tennis_url(page_num):
    page_url = 'https://s5.sir.sportradar.com/sportradar/en/5/season/' + str(page_num)
    soup = get_soup_object(page_url)
    if 'Tennis' in soup.text:
        return page_url

tennis_urls = []

with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
    future_to_page_num = {executor.submit(check_tennis_url, page_num): page_num for page_num in range(97274, 100000)}
    for i, future in enumerate(concurrent.futures.as_completed(future_to_page_num), 1):
        page_num = future_to_page_num[future]
        try:
            tennis_url = future.result()
            if tennis_url:
                tennis_urls.append(tennis_url)
        except Exception as exc:
            print(f"Page {page_num} generated an exception: {exc}")

        if i % 5000 == 0:
            print(f"{i} page numbers checked")

In [ ]:
tennis_urls = pd.DataFrame(tennis_urls1)

In [ ]:
tennis_urls

['https://s5.sir.sportradar.com/sportradar/en/5/season/97281',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97279',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97275',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97283',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97277',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97285',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97287',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97291',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97289',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97293',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97295',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97299',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97297',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97301',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97303',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97305',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97307',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97309',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97311',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97313',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97315',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97319',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97317',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97321',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97323',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97325',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97327',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97329',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97331',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97333',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97335',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97337',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97339',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97341',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97343',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97345',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97347',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97349',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97351',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97353',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97355',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97357',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97359',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97431',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97433',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97471',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97473',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97475',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97477',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97479',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97481',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97483',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97485',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97487',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97489',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97491',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97495',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97493',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97497',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97499',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97503',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97501',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97505',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97507',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97509',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97511',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97513',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97517',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97519',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97521',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97523',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97525',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97531',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97529',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97533',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97535',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97537',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97541',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97539',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97543',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97545',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97547',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97549',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97551',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97553',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97557',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97555',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97559',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97561',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97563',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97565',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97645',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97653',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97655',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/97659',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98483',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98479',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98487',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98485',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98489',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98493',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98491',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98495',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98497',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98501',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98505',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98503',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98507',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98509',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98511',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98515',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98517',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98519',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98523',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98527',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98529',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98525',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98531',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98533',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98535',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98539',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98537',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98541',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98543',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98545',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98547',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98551',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98555',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98559',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98561',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98565',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98569',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98567',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98571',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98573',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98577',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98581',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98579',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98609',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98641',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98643',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98645',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98647',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98649',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98663',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98665',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98669',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98667',
 'https://s5.sir.sportradar.com/sportradar/en/5/season/98671']

In [ ]:
tennis_urls1 = pd.read_csv('tennis_tournament_urls.csv')

In [ ]:
tennis_urls1

                                                     0
0    https://s5.sir.sportradar.com/sportradar/en/5/...
1    https://s5.sir.sportradar.com/sportradar/en/5/...
2    https://s5.sir.sportradar.com/sportradar/en/5/...
3    https://s5.sir.sportradar.com/sportradar/en/5/...
4    https://s5.sir.sportradar.com/sportradar/en/5/...
..                                                 ...
546  https://s5.sir.sportradar.com/sportradar/en/5/...
547  https://s5.sir.sportradar.com/sportradar/en/5/...
548  https://s5.sir.sportradar.com/sportradar/en/5/...
549  https://s5.sir.sportradar.com/sportradar/en/5/...
550  https://s5.sir.sportradar.com/sportradar/en/5/...

[551 rows x 1 columns]