# Data Cleaning

In [6]:
import pandas as pd

In [11]:
df = pd.read_csv('all_matches.csv')

C:\Users\samke\AppData\Local\Temp\ipykernel_12792\2722818001.py:1: DtypeWarning: Columns (5,8,10,45,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('all_matches.csv')

In [12]:
df

,start_date,end_date,location,court_surface,prize_money,currency,year,player_id,player_name,opponent_id,...,total_points,duration,player_victory,retirement,seed,won_first_set,doubles,masters,round_num,nation
0,2012-06-11,2012-06-17,Slovakia,Clay,30000.0,€,2012,adrian-partl,A. Partl,andrej-martin,...,88.0,01:02:00,f,f,NaN,f,f,100,1,Slovakia
1,2012-06-11,2012-06-17,Slovakia,Clay,30000.0,€,2012,adrian-partl,A. Partl,jozef-kovalik,...,195.0,02:43:00,t,f,NaN,t,f,100,0,Slovakia
2,2012-06-11,2012-06-17,Slovakia,Clay,30000.0,€,2012,agustin-velotti,A. Velotti,dominik-hrbaty,...,126.0,01:17:00,f,f,NaN,f,f,100,3,Slovakia
3,2012-06-11,2012-06-17,Slovakia,Clay,30000.0,€,2012,agustin-velotti_marcel-felder,NaN,andrei-daescu_florin-mergea,...,NaN,NaN,f,f,NaN,t,t,100,4,Slovakia
4,2012-06-11,2012-06-17,Slovakia,Clay,30000.0,€,2012,alessandro-giannessi,A. Giannessi,harri-heliovaara,...,194.0,02:32:00,t,f,1,t,f,100,3,Slovakia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4295822,2010-10-18,2010-10-22,DEN,Carpet,NaN,NaN,2010,tom-georg-hjertonsson,NaN,axel-helisten,...,NaN,NaN,t,f,NaN,t,f,0,0,DEN
4295823,2010-10-18,2010-10-22,DEN,Carpet,NaN,NaN,2010,tom-georg-hjertonsson,NaN,karl-eirik-wangensten-oye,...,NaN,NaN,f,f,NaN,f,f,0,1,DEN
4295824,2010-10-18,2010-10-22,DEN,Carpet,NaN,NaN,2010,william-baan,NaN,callum-poland-smith,...,NaN,NaN,t,f,NaN,t,f,0,4,DEN
4295825,2010-10-18,2010-10-22,DEN,Carpet,NaN,NaN,2010,william-baan,NaN,casper-melskens,...,NaN,NaN,f,f,NaN,f,f,0,5,DEN
4295826,2010-10-18,2010-10-22,DEN,Carpet,NaN,NaN,2010,william-baan,NaN,jelle-sels,...,NaN,NaN,t,f,NaN,t,f,0,3,DEN

In [14]:
df['start_date'] = pd.to_datetime(df['start_date'])

In [18]:
df = df.sort_values(by='start_date')

In [19]:
df.head()

,start_date,end_date,location,court_surface,prize_money,currency,year,player_id,player_name,opponent_id,...,total_points,duration,player_victory,retirement,seed,won_first_set,doubles,masters,round_num,nation
2832263,1950-01-21,1950-01-30,Australia,Hard,NaN,NaN,1950,eric-william-sturgess,NaN,frank-lonergan,...,NaN,NaN,t,f,2,t,f,2000,3,Australia
2832278,1950-01-21,1950-01-30,Australia,Hard,NaN,NaN,1950,harry-hopman,NaN,george-worthington,...,NaN,NaN,f,f,NaN,t,f,2000,4,Australia
2832279,1950-01-21,1950-01-30,Australia,Hard,NaN,NaN,1950,harry-hopman,NaN,keith-rogers,...,NaN,NaN,t,f,NaN,t,f,2000,3,Australia
2832280,1950-01-21,1950-01-30,Australia,Hard,NaN,NaN,1950,h.-raward,NaN,ian-occleshaw,...,NaN,NaN,f,f,NaN,f,f,2000,2,Australia
2832281,1950-01-21,1950-01-30,Australia,Hard,NaN,NaN,1950,ian-ayre,NaN,ken-mcgregor,...,NaN,NaN,f,f,NaN,f,f,2000,3,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926771,2018-08-22,2018-08-26,AUS,Hard,NaN,NaN,2018,dane-sweeny,NaN,kelvin-du,...,NaN,NaN,t,NaN,1,t,f,0,3,AUS
2926770,2018-08-22,2018-08-26,AUS,Hard,NaN,NaN,2018,dane-sweeny,NaN,jin-gu,...,NaN,NaN,t,NaN,1,t,f,0,4,AUS
2926768,2018-08-22,2018-08-26,AUS,Hard,NaN,NaN,2018,cooper-white,NaN,shuannon-tricerri,...,NaN,NaN,f,NaN,NaN,t,f,0,3,AUS
2926766,2018-08-22,2018-08-26,AUS,Hard,NaN,NaN,2018,connor-johnson,NaN,shuannon-tricerri,...,NaN,NaN,t,NaN,NaN,f,f,0,4,AUS
2926740,2018-08-22,2018-08-26,AUS,Hard,NaN,NaN,2018,alex-carroll,NaN,man-san-chan,...,NaN,NaN,t,NaN,NaN,t,f,0,2,AUS